-- Run this to add missing algorithms to an existing database
-- Usage: docker exec -i hash-brother-hood-db-1 psql -U hashbro -d hashbrotherhood < add_algorithms.sql

INSERT INTO algorithms (name, display_name, unit) VALUES
    ('sha256asicboost', 'SHA-256 AsicBoost', 'TH/s'),
    ('sha256dt', 'SHA-256DT', 'TH/s'),
    ('sha512256d', 'SHA512/256d', 'TH/s'),
    ('scryptnf', 'ScryptNf', 'GH/s'),
    ('ubqhash', 'Ubqhash', 'MH/s'),
    ('ethashb3', 'EthashB3', 'MH/s'),
    ('equihash1254', 'Equihash 125,4', 'Sol/s'),
    ('equihash1445', 'Equihash 144,5', 'Sol/s'),
    ('equihash1505', 'Equihash 150,5', 'Sol/s'),
    ('equihash1927', 'Equihash 192,7', 'Sol/s'),
    ('equihash2109', 'Equihash 210,9', 'Sol/s'),
    ('zhash', 'ZHash', 'Sol/s'),
    ('beamhashiii', 'BeamHash III', 'Sol/s'),
    ('blake256r14', 'Blake256r14', 'GH/s'),
    ('blake2bsia', 'Blake2b-Sia', 'GH/s'),
    ('blake2skadena', 'Blake2s-Kadena', 'GH/s'),
    ('blake3dcr', 'Blake3-Decred', 'GH/s'),
    ('progpowz', 'ProgPowZ', 'MH/s'),
    ('evrprogpow', 'EvrProgPow', 'MH/s'),
    ('meowpow', 'MeowPow', 'MH/s'),
    ('cuckaroo29', 'Cuckaroo29', 'G/s'),
    ('cuckatoo31', 'Cuckatoo31', 'G/s'),
    ('cortex', 'Cortex', 'G/s'),
    ('randomsfx', 'RandomSFX', 'H/s'),
    ('randomwow', 'RandomWOW', 'H/s'),
    ('randomarq', 'RandomARQ', 'H/s'),
    ('cryptonightv8', 'CryptoNightV8', 'H/s'),
    ('cryptonightheavy', 'CryptoNightHeavy', 'H/s'),
    ('cryptonightgpu', 'CryptoNightGPU', 'H/s'),
    ('cryptonighthaven', 'CryptoNightHaven', 'H/s'),
    ('cryptonightconceal', 'CryptoNightConceal', 'H/s'),
    ('x11gost', 'X11Gost', 'GH/s'),
    ('x16rt', 'X16RT', 'MH/s'),
    ('x21s', 'X21S', 'MH/s'),
    ('x25x', 'X25X', 'MH/s'),
    ('lyra2rev2', 'Lyra2REv2', 'MH/s'),
    ('karlsenhash', 'KarlsenHash', 'GH/s'),
    ('yescryptr16', 'YescryptR16', 'KH/s'),
    ('yescryptr32', 'YescryptR32', 'KH/s'),
    ('yespowersugar', 'YesPowerSUGAR', 'KH/s'),
    ('argon2d', 'Argon2d', 'KH/s'),
    ('argon2dnim', 'Argon2d-NIM', 'KH/s'),
    ('chukwa', 'Chukwa', 'KH/s'),
    ('fishhash', 'FishHash', 'MH/s'),
    ('nexapow', 'NexaPoW', 'MH/s'),
    ('dynexsolve', 'DynexSolve', 'MH/s'),
    ('xelishash', 'XelisHash', 'MH/s'),
    ('radiant', 'Radiant', 'GH/s'),
    ('zksnark', 'zkSNARK', 'H/s'),
    ('lbry', 'LBRY', 'GH/s'),
    ('sia', 'Sia', 'GH/s'),
    ('decred', 'Decred', 'GH/s'),
    ('odocrypt', 'Odocrypt', 'MH/s'),
    ('astrobwtv2', 'AstroBWTv2', 'KH/s'),
    ('verushash', 'VerusHash', 'MH/s'),
    ('myrgroestl', 'Myr-Groestl', 'MH/s'),
    ('quark', 'Quark', 'GH/s'),
    ('xevan', 'Xevan', 'MH/s'),
    ('hmq1725', 'HMQ1725', 'MH/s'),
    ('skunk', 'Skunk', 'GH/s')
ON CONFLICT (name) DO NOTHING;

-- Fix units for algorithms that had wrong units
UPDATE algorithms SET unit = 'H/s' WHERE name = 'randomx';
UPDATE algorithms SET unit = 'H/s' WHERE name = 'cryptonight';
UPDATE algorithms SET unit = 'H/s' WHERE name IN ('cryptonightR', 'cryptonightr');
UPDATE algorithms SET unit = 'H/s' WHERE name = 'ghostrider';
